/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Evento;

import modelo.ListaEvento;
import modelo.Usuario;

/**
 *
 * @author nando
 */
public class CadastrarEvento extends javax.swing.JFrame {

    String nome, local, data, assunto, temp_string;
    ArrayList<Evento> temp = new ArrayList<>();
    ListaEvento a1 = new ListaEvento(temp);
    
    /**
     * Creates new form CadastrarEvento
     */
    public CadastrarEvento() {
        initComponents();
    }
    
    public boolean ConfirmaCamposObrigatorios(){
        if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Campo Nome Obrigatório","Aviso",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(txtdata.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Campo Data Obrigatório","Aviso",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(txtlocal.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Campo Local Obrigatório","Aviso",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else if(txtassunto.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Campo Assunto Obrigatório","Aviso",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        else{
            return true;
        }
    }
    
        private void LimparCadastroEvento(){
        txtnome.setText("");
        txtdata.setText("");
        txtassunto.setText("");
        txtlocal.setText("");
        txtnome.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcadastrarevento = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        lbdata = new javax.swing.JLabel();
        lbassunto = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtdata = new javax.swing.JTextField();
        txtassunto = new javax.swing.JTextField();
        btconfirmar = new javax.swing.JButton();
        btlimpar = new javax.swing.JButton();
        btvoltar = new javax.swing.JButton();
        lbassunto1 = new javax.swing.JLabel();
        txtlocal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbcadastrarevento.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbcadastrarevento.setText("Cadastrar Evento");

        lbnome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome.setText("Nome do evento:");

        lbdata.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbdata.setText("Data do evento:");

        lbassunto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbassunto.setText("Assunto:");

        btconfirmar.setText("Confirmar");
        btconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconfirmarActionPerformed(evt);
            }
        });

        btlimpar.setText("Limpar");
        btlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlimparActionPerformed(evt);
            }
        });

        btvoltar.setText("Voltar");
        btvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoltarActionPerformed(evt);
            }
        });

        lbassunto1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbassunto1.setText("Local do evento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btvoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbdata)
                            .addComponent(lbassunto))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdata, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(txtassunto, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbassunto1)
                        .addGap(18, 18, 18)
                        .addComponent(txtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbcadastrarevento))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbnome)
                        .addGap(18, 18, 18)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbcadastrarevento)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbassunto1)
                    .addComponent(txtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdata)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbassunto)
                    .addComponent(txtassunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btconfirmar)
                    .addComponent(btlimpar)
                    .addComponent(btvoltar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoltarActionPerformed
        MenuFuncionario menufunc = new MenuFuncionario();
        this.setVisible(false);
        menufunc.setLocationRelativeTo(null);
        menufunc.setVisible(true);
    }//GEN-LAST:event_btvoltarActionPerformed

    private void btlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlimparActionPerformed
        LimparCadastroEvento();
        
    }//GEN-LAST:event_btlimparActionPerformed

    private void btconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconfirmarActionPerformed
        boolean temp = ConfirmaCamposObrigatorios();
        if(temp == true){
            a1.carregarEventos();
            nome = this.txtnome.getText();
            local = this.txtlocal.getText();
            data = this.txtdata.getText();
            assunto = this.txtassunto.getText();
            
            a1.cadastrar(new Evento(nome, local, data, assunto));
            a1.salvarEvento();
            JOptionPane.showMessageDialog(rootPane,"Cadastro de evento realizado!");
        }
        LimparCadastroEvento();
       
    }//GEN-LAST:event_btconfirmarActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btconfirmar;
    private javax.swing.JButton btlimpar;
    private javax.swing.JButton btvoltar;
    private javax.swing.JLabel lbassunto;
    private javax.swing.JLabel lbassunto1;
    private javax.swing.JLabel lbcadastrarevento;
    private javax.swing.JLabel lbdata;
    private javax.swing.JLabel lbnome;
    private javax.swing.JTextField txtassunto;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtlocal;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
