/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modelo.*;
import java.util.ArrayList;

/**
 *
 * @author xiuki
 */
public class CatalogoPedido extends javax.swing.JFrame {
    
    
    Usuario currentUser = new Usuario();
    String titulo, subtitulo, autor, isbn, assuntos,
           edicao, editora, local, paginas, cdd, cdu, nomeUsuario;
    
    Catalografica a1 = new Catalografica();
    ArrayList<Catalografica> lista = new ArrayList<>();
    ListaCatalogo b1 = new ListaCatalogo(lista);
    
    /**
     * Creates new form CataloPedido
     */
    public CatalogoPedido() {
        initComponents();
    }
    
    public CatalogoPedido(Usuario dados) {
        initComponents();
        
        //  Passar dados para o Usuario currentUser
        currentUser.setNome(dados.getNome());
        currentUser.setNome_usuario(dados.getNomeUsuario());
        currentUser.setPermissao(dados.getPermissao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbcadastrodeusuario = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lbnome1 = new javax.swing.JLabel();
        txtSubtitulo = new javax.swing.JTextField();
        lbnome2 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lbnome3 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        lbnome4 = new javax.swing.JLabel();
        txtAssuntos = new javax.swing.JTextField();
        lbnome5 = new javax.swing.JLabel();
        txtEdicao = new javax.swing.JTextField();
        lbnome6 = new javax.swing.JLabel();
        txtEditora = new javax.swing.JTextField();
        lbnome7 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        lbnome8 = new javax.swing.JLabel();
        txtPaginas = new javax.swing.JTextField();
        lbnome9 = new javax.swing.JLabel();
        txtCdd = new javax.swing.JTextField();
        lbnome10 = new javax.swing.JLabel();
        txtCdu = new javax.swing.JTextField();
        solicitar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbcadastrodeusuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbcadastrodeusuario.setText("Solicitar Ficha Catalográfica");

        lbnome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome.setText("Titulo:");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        lbnome1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome1.setText("Subtítulo:");

        txtSubtitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtituloActionPerformed(evt);
            }
        });

        lbnome2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome2.setText("Autor:");

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        lbnome3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome3.setText("ISBN:");

        txtIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsbnActionPerformed(evt);
            }
        });

        lbnome4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome4.setText("Assuntos:");

        txtAssuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssuntosActionPerformed(evt);
            }
        });

        lbnome5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome5.setText("Edição:");

        txtEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicaoActionPerformed(evt);
            }
        });

        lbnome6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome6.setText("Editora:");

        txtEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditoraActionPerformed(evt);
            }
        });

        lbnome7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome7.setText("Local:");

        txtLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalActionPerformed(evt);
            }
        });

        lbnome8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome8.setText("Páginas:");

        txtPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginasActionPerformed(evt);
            }
        });

        lbnome9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome9.setText("CDD:");

        txtCdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCddActionPerformed(evt);
            }
        });

        lbnome10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbnome10.setText("CDU:");

        txtCdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCduActionPerformed(evt);
            }
        });

        solicitar.setText("Solicitar");
        solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lbcadastrodeusuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbnome6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbnome2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbnome1)
                                        .addComponent(lbnome))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbnome3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbnome7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbnome5)
                                        .addGap(42, 42, 42))
                                    .addComponent(lbnome4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAssuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnome8)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnome9)
                                .addGap(18, 18, 18)
                                .addComponent(txtCdd, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(solicitar)
                                .addGap(64, 64, 64)
                                .addComponent(voltar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnome10)
                                .addGap(18, 18, 18)
                                .addComponent(txtCdu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbcadastrodeusuario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnome)
                    .addComponent(lbnome10)
                    .addComponent(txtCdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome1)
                    .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome2)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome3)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbnome4)
                            .addComponent(txtAssuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbnome5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome6)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome7)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome8)
                    .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnome9)
                    .addComponent(txtCdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solicitar)
                    .addComponent(voltar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtSubtituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtituloActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnActionPerformed

    private void txtAssuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssuntosActionPerformed

    private void txtEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicaoActionPerformed

    private void txtEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditoraActionPerformed

    private void txtLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalActionPerformed

    private void txtPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginasActionPerformed

    private void txtCddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCddActionPerformed

    private void txtCduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCduActionPerformed

    private void solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarActionPerformed
        // TODO add your handling code here:
        titulo = txtTitulo.getText();
        subtitulo = txtSubtitulo.getText();
        autor = txtAutor.getText();
        isbn = txtIsbn.getText(); 
        assuntos = txtAssuntos.getText();
        edicao = txtEdicao.getText(); 
        editora = txtEditora.getText();
        local = txtLocal.getText(); 
        paginas = txtPaginas.getText(); 
        cdd = txtCdd.getText();
        cdu = txtCdu.getText(); 
        nomeUsuario = currentUser.getNomeUsuario();
        
        a1 = new Catalografica(titulo, subtitulo, autor, 
                isbn, assuntos, edicao, editora, 
                local, paginas, cdd, cdu, nomeUsuario);
        
        b1.carregarPedidos();
        b1.getLista().add(a1);
        b1.salvarPedidos();
    }//GEN-LAST:event_solicitarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
            MenuUsuario menu = new MenuUsuario(currentUser);
            this.setVisible(false);
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbcadastrodeusuario;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbnome1;
    private javax.swing.JLabel lbnome10;
    private javax.swing.JLabel lbnome2;
    private javax.swing.JLabel lbnome3;
    private javax.swing.JLabel lbnome4;
    private javax.swing.JLabel lbnome5;
    private javax.swing.JLabel lbnome6;
    private javax.swing.JLabel lbnome7;
    private javax.swing.JLabel lbnome8;
    private javax.swing.JLabel lbnome9;
    private javax.swing.JButton solicitar;
    private javax.swing.JTextField txtAssuntos;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCdd;
    private javax.swing.JTextField txtCdu;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtSubtitulo;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
